version: '3'

services:
  ansible:
    build:
      context: ./ansible
      args:
        - USER
    image:
      mdoansible:mdo
    volumes:
      - /d/VirtualBox/Ubuntu/SharedFolder:/home/ansible
    stdin_open: true
    tty: true
    command: tail -f /dev/null
